### ISSUE TITLE
AttributeError: 'function' object has no attribute 'func_code'

### ISSUE THREAD

**Issue by oriolcolomefont** [Spijkervet/audio-augmentations#17]
Hey there!
Thanks for the work! When importing the package I get `AttributeError: 'function' object has no attribute 'func_code'`

Could you please shed some light on this?

Thanks!

**Comment by nathan0neal** [comment]
I've ran into the same issue. I think it might be linked to us using Python 3 instead of Python 2

**Comment by Ying156209** [comment]
Install 'augment' by [https://github.com/facebookresearch/WavAugment](WavAugment).   You are not using the right augment module.

**Comment by oriolcolomefont** [comment]
Thank you!
