### ISSUE TITLE
Default value of `max_snr` in `Noise` 

### ISSUE THREAD

**Issue by keunwoochoi** [Spijkervet/audio-augmentations#4]
1.0 of SNR with signal and white noise would be a really heavily corrupted signal. Could we set it to be a little more reasonable value?

Related; it'd be great if one can hear some examples of the augmented result.

**Comment by Spijkervet** [comment]
Agreed! :) I can see if I can render some examples

**Comment by Spijkervet** [comment]
Updated the defaults in https://github.com/Spijkervet/torchaudio-augmentations/commit/956000e069008f5e6b412eb135fe1bcf04b00053

There are some amazing demos in this tutorial notebook I found ;)
https://music-classification.github.io/tutorial/part3_supervised/data-augmentation.html

I'll see if I can transfer a few to this README.
