### ISSUE TITLE
Correctness unit test would be great

### ISSUE THREAD

**Issue by keunwoochoi** [Spijkervet/audio-augmentations#5]
For some transforms, we can test if the values are actually correct by manually computing the expected value. For example, `PolarityInversion` could be test with some tiny tensors like [[0.1, 0.5, -1.0]]. `Reverse` as well. Probably only those two? Still, it'd be better than not having any.

**Comment by Spijkervet** [comment]
I currently test the PolarityInversion in: https://github.com/Spijkervet/torchaudio-augmentations/blob/master/tests/test_augmentations.py#L43

I agree I should have tested it with an explicitly defined vector rather than relying on torch.neg() here. Same applies for Reverse(). I'll add these!

**Comment by Spijkervet** [comment]
Addressed in https://github.com/Spijkervet/torchaudio-augmentations/commit/b2065b89f82ead73c7ff7d12ffa3250bc161c616 :D 

(For mono, stereo and batched audio)
