### ISSUE TITLE
Delay augmentation on cuda

### ISSUE THREAD

**Issue by sidml** [Spijkervet/audio-augmentations#8]
Hi.
Currently the delay augmentation doesn't work on gpu since part of the signal is on cpu.
I think making the` beginning` tensor  same as the `audio` tensor device should fix it. Thanks.
https://github.com/Spijkervet/torchaudio-augmentations/blob/d044f9d020e12032ab9280acf5f34a337e72d212/torchaudio_augmentations/augmentations/delay.py#L31

**Comment by Spijkervet** [comment]
We can also cast this tensor to the audio tensor's device, I think.

**Comment by Spijkervet** [comment]
Fixed in f3e0ad8
